/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'frequent_user.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'frequent_user.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./frequent_user.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedFrequentDateStart").onDelete = 'CASCADE'; 
util.getAttribute("userId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.frequentUser",
    options: {
        tableName: "frequent_user",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "userId": {
            type: Seq.INTEGER,
            field: "user_id",
            primaryKey: true,
            allowNull: false,
            unique: "frequent_user_pk",
            references: "public.user",
            referencesKey: "user_id"
        },
        "placeId": {
            type: Seq.INTEGER,
            field: "place_id",
            primaryKey: true,
            allowNull: false,
            unique: "frequent_user_pk",
            references: "public.place",
            referencesKey: "place_id"
        },
        "frequentDateStart": {
            type: Seq.DATEONLY,
            field: "frequent_date_start",
            primaryKey: true,
            allowNull: false,
            unique: "frequent_user_pk",
            references: "public.frequentDate",
            referencesKey: "frequent_date_start"
        },
        "frequentUserDateEnd": {
            type: Seq.DATEONLY,
            field: "frequent_user_date_end",
            allowNull: false
        },
        "frequentUserVisibility": {
            type: Seq.STRING(250),
            field: "frequent_user_visibility",
            allowNull: false
        },
        "frequentUserFeedback": {
            type: Seq.STRING(250),
            field: "frequent_user_feedback"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.frequentDate",
        schema: "public",
        table: "frequent_date",
        source: "generator",
        details: {
            as: "relatedFrequentDateStart",
            foreignKey: "frequent_date_start",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.place",
        schema: "public",
        table: "place",
        source: "generator",
        details: {
            as: "place",
            foreignKey: "place_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.user",
        schema: "public",
        table: "user",
        source: "generator",
        details: {
            as: "user",
            foreignKey: "user_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};