/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'SequelizeMeta.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'SequelizeMeta.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./SequelizeMeta.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("name").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.sequelizeMeta",
    options: {
        tableName: "SequelizeMeta",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "name": {
            type: Seq.STRING(255),
            field: "name",
            primaryKey: true,
            allowNull: false,
            unique: "SequelizeMeta_pkey"
        }
    },
    relations: []
};