/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'frequent_date.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'frequent_date.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./frequent_date.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("frequentGroupFrequentDate1Fks").onDelete = 'CASCADE'; 
util.getAttribute("frequentDateStart").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.frequentDate",
    options: {
        tableName: "frequent_date",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "frequentDateStart": {
            type: Seq.DATEONLY,
            field: "frequent_date_start",
            primaryKey: true,
            allowNull: false,
            unique: "frequent_date_pk"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.frequentGroup",
        schema: "public",
        table: "frequent_group",
        source: "generator",
        details: {
            as: "frequentGroupFrequentDate1Fks",
            foreignKey: "frequent_date_start",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.frequentUser",
        schema: "public",
        table: "frequent_user",
        source: "generator",
        details: {
            as: "frequentUserFrequentDate1Fks",
            foreignKey: "frequent_date_start",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.group",
        schema: "public",
        table: "group",
        source: "generator",
        details: {
            as: "frequentGroupFrequentDate1FkGroups",
            foreignKey: "frequent_date_start",
            otherKey: "group_id",
            through: "frequent_group",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.place",
        schema: "public",
        table: "place",
        source: "generator",
        details: {
            as: "frequentGroupFrequentDate1FkPlaces",
            foreignKey: "frequent_date_start",
            otherKey: "place_id",
            through: "frequent_group",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.place",
        schema: "public",
        table: "place",
        source: "generator",
        details: {
            as: "frequentUserFrequentDate1FkPlaces",
            foreignKey: "frequent_date_start",
            otherKey: "place_id",
            through: "frequent_user",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.user",
        schema: "public",
        table: "user",
        source: "generator",
        details: {
            as: "frequentUserFrequentDate1FkUsers",
            foreignKey: "frequent_date_start",
            otherKey: "user_id",
            through: "frequent_user",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};