/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this models:
1. Create 'group.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'group.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    models   = require('./group.js'),
    util    = require('../utils.js')(models),
    Seq     = orm.Sequelize();

module.exports = models;

// Some utility methods:
util.getRelation("frequentGroup1Fks").onDelete = 'CASCADE'; 
util.getAttribute("groupId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.group",
    options: {
        tableName: "group",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "groupId": {
            type: Seq.INTEGER,
            field: "group_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "group_pk"
        },
        "groupName": {
            type: Seq.STRING(25),
            field: "group_name",
            allowNull: false
        },
        "groupDescription": {
            type: Seq.STRING(250),
            field: "group_description",
            allowNull: false
        },
        "groupPicture": {
            type: Seq.BLOB,
            field: "group_picture",
            allowNull: false
        },
        "groupDateCreation": {
            type: Seq.DATEONLY,
            field: "group_date_creation",
            allowNull: false
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.frequent",
        schema: "public",
        table: "frequent",
        source: "generator",
        details: {
            as: "frequentGroup1Fks",
            foreignKey: "group_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.own",
        schema: "public",
        table: "own",
        source: "generator",
        details: {
            as: "ownGroupFks",
            foreignKey: "group_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.participate",
        schema: "public",
        table: "participate",
        source: "generator",
        details: {
            as: "participateGroupFks",
            foreignKey: "group_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.place",
        schema: "public",
        table: "place",
        source: "generator",
        details: {
            as: "frequentGroup1FkPlaces",
            foreignKey: "group_id",
            otherKey: "place_id",
            through: "frequent",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.user",
        schema: "public",
        table: "user",
        source: "generator",
        details: {
            as: "frequentGroup1FkUsers",
            foreignKey: "group_id",
            otherKey: "user_id",
            through: "frequent",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.user",
        schema: "public",
        table: "user",
        source: "generator",
        details: {
            as: "ownGroupFkUsers",
            foreignKey: "group_id",
            otherKey: "user_id",
            through: "own",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.user",
        schema: "public",
        table: "user",
        source: "generator",
        details: {
            as: "participateGroupFkUsers",
            foreignKey: "group_id",
            otherKey: "user_id",
            through: "participate",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};