/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'belong.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'belong.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./belong.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("place").onDelete = 'CASCADE'; 
util.getAttribute("typeId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.belong",
    options: {
        tableName: "belong",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "typeId": {
            type: Seq.INTEGER,
            field: "type_id",
            primaryKey: true,
            allowNull: false,
            unique: "belong_pk",
            references: "public.type",
            referencesKey: "type_id"
        },
        "placeId": {
            type: Seq.INTEGER,
            field: "place_id",
            primaryKey: true,
            allowNull: false,
            unique: "belong_pk",
            references: "public.place",
            referencesKey: "place_id"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.place",
        schema: "public",
        table: "place",
        source: "generator",
        details: {
            as: "place",
            foreignKey: "place_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.type",
        schema: "public",
        table: "type",
        source: "generator",
        details: {
            as: "type",
            foreignKey: "type_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};