/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this models:
1. Create 'frequent.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'frequent.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('models\index.js'),
    models   = require('./frequent.js'),
    util    = require('../utils.js')(models),
    Seq     = orm.Sequelize();

module.exports = models;

// Some utility methods:
util.getRelation("group").onDelete = 'CASCADE'; 
util.getAttribute("userId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.frequent",
    options: {
        tableName: "frequent",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "userId": {
            type: Seq.INTEGER,
            field: "user_id",
            primaryKey: true,
            allowNull: false,
            unique: "frequent_pk",
            references: "public.user",
            referencesKey: "user_id"
        },
        "placeId": {
            type: Seq.INTEGER,
            field: "place_id",
            primaryKey: true,
            allowNull: false,
            unique: "frequent_pk",
            references: "public.place",
            referencesKey: "place_id"
        },
        "groupId": {
            type: Seq.INTEGER,
            field: "group_id",
            primaryKey: true,
            allowNull: false,
            unique: "frequent_pk",
            references: "public.group",
            referencesKey: "group_id"
        },
        "frequentDateStart": {
            type: Seq.DATEONLY,
            field: "frequent_date_start",
            allowNull: false
        },
        "frequentDateEnd": {
            type: Seq.DATEONLY,
            field: "frequent_date_end",
            allowNull: false
        },
        "frequentVisibility": {
            type: Seq.STRING(20),
            field: "frequent_visibility",
            allowNull: false
        },
        "frequentFeedback": {
            type: Seq.STRING(250),
            field: "frequent_feedback",
            allowNull: false
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.group",
        schema: "public",
        table: "group",
        source: "generator",
        details: {
            as: "group",
            foreignKey: "group_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.place",
        schema: "public",
        table: "place",
        source: "generator",
        details: {
            as: "place",
            foreignKey: "place_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.user",
        schema: "public",
        table: "user",
        source: "generator",
        details: {
            as: "user",
            foreignKey: "user_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};